#!/usr/bin/env node
/* Compile RootRegistry.sol and write the artifact the dashboard embeds.
   Usage: cd contracts && npm install && npm run build
   Output: dashboard/registry-artifact.js  (ABI, bytecode, selectors, event topic)
           contracts/out/RootRegistry.json (full solc output for verification) */
"use strict";

const fs = require("fs");
const path = require("path");
const solc = require("solc");
const { id, Interface } = require("ethers");

const SRC = path.join(__dirname, "RootRegistry.sol");
const OUT_DIR = path.join(__dirname, "out");
const ARTIFACT = path.join(__dirname, "..", "dashboard", "registry-artifact.js");

const source = fs.readFileSync(SRC, "utf8");
const input = {
  language: "Solidity",
  sources: { "RootRegistry.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    // Paris: no PUSH0, no transient storage. Keeps bytecode portable across FEVM versions.
    evmVersion: "paris",
    metadata: { bytecodeHash: "none" },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object", "evm.methodIdentifiers", "metadata"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors || []).filter((e) => e.severity === "error");
if (errors.length) {
  errors.forEach((e) => console.error(e.formattedMessage));
  process.exit(1);
}
(output.errors || []).forEach((e) => console.warn(e.formattedMessage));

const c = output.contracts["RootRegistry.sol"].RootRegistry;
const iface = new Interface(c.abi);
const eventTopic = id("RootAttested(bytes32,address,uint64,uint64,string,uint256)");
const attestSelector = "0x" + c.evm.methodIdentifiers["attest(bytes32,uint64,uint64,string)"];
const attestationSelector = "0x" + c.evm.methodIdentifiers["attestation(bytes32)"];
const isAttestedSelector = "0x" + c.evm.methodIdentifiers["isAttested(bytes32)"];
const countSelector = "0x" + c.evm.methodIdentifiers["count()"];

if (iface.getEvent("RootAttested").topicHash !== eventTopic) throw new Error("event topic mismatch");

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  path.join(OUT_DIR, "RootRegistry.json"),
  JSON.stringify({ abi: c.abi, bytecode: "0x" + c.evm.bytecode.object, deployedBytecode: "0x" + c.evm.deployedBytecode.object, metadata: JSON.parse(c.metadata), compiler: solc.version(), evmVersion: "paris", optimizer: { enabled: true, runs: 200 } }, null, 2),
);

const banner = `/* Generated by contracts/build.js from contracts/RootRegistry.sol
   solc ${solc.version()} · evmVersion paris · optimizer 200 runs
   Do not edit by hand. Rebuild with: cd contracts && npm run build */\n`;
const artifact = {
  name: "RootRegistry",
  compiler: solc.version(),
  evmVersion: "paris",
  abi: c.abi,
  bytecode: "0x" + c.evm.bytecode.object,
  selectors: { attest: attestSelector, attestation: attestationSelector, isAttested: isAttestedSelector, count: countSelector },
  topics: { RootAttested: eventTopic },
};
fs.writeFileSync(ARTIFACT, banner + "window.IQC_REGISTRY = " + JSON.stringify(artifact, null, 2) + ";\n");

console.log("bytecode bytes:", c.evm.bytecode.object.length / 2);
console.log("attest selector:", attestSelector);
console.log("RootAttested topic:", eventTopic);
console.log("wrote", path.relative(process.cwd(), ARTIFACT));
